### PR TITLE
Fix http-proxy invocation

### PR DESCRIPTION
**Pull request by paulirish**
Before:
image

after: 
image

### CODE REVIEW

**Comment by thlorenz** [comment]
Thanks a bunch ... LGTM, will merge tomorrow.
Haven't used this for a while and thought I was the only user :)

Is this useful to you as well? Would be interested to hear what for ...

**Comment by thlorenz** [comment]
Looks like you made `index.js` and `visualize.js` executable. I guess just while testing this? Or on purpose?
The binaries are exposed via `crdp` and `crdp-visualize` in the `bin` section of the package.json and thus made executable on `npm install`.
Will revert that part but keep the version bump unless you have a need for them to be executable.

**Comment by thlorenz** [comment]
Updated the http-proxy version at 2372f11e08945750cdded66b9fccc8458db35676.

Thanks for the PR ... didn't merge the file mode changes.

**Comment by paulirish** [comment]
sounds good dude. thanks for that!

I ended up not being able to make this work in the end, though. :/

Here's what i remember from my debug session earlier: For some reason the hybi was rejecting some early frames as they had a reserved bit set, and so it called shutdown() and then no more messages were emitted, even though the data was going into parse().

I ended up just hooking into chrome-remote-interface's events and logging there. It's a layer higher than I wanted, but the upside is I didn't need to figure out how websocket frames work. :)

**Pull request closed without merging**
